[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/index.php*"
  to = "/"

[[redirects]]
  from = "/about.html"
  to = "/about/"

[[redirects]]
  from = "/pmops/classes/"
  to = "/pmops/classes/classes_1/"
